export const data = {
  routes: [
    {
      id: 1,
      width: 112,
      height: 112,
      src: "/user/user-02.png",
      alt: "User",
      name: "Mariya Desoja",
      description: "I like your confidence 💪",
      ago: "2min ago",
    },
    {
      id: 2,
      width: 112,
      height: 112,
      src: "/user/user-01.png",
      alt: "User",
      name: "Robert Jhon",
      description: "Can you share your offer?",
      ago: "10min ago",
    },
    {
      id: 3,
      width: 112,
      height: 112,
      src: "/user/user-03.png",
      alt: "User",
      name: "Henry Dholi",
      description: "I cam across your profile and...",
      ago: "1day ago",
    },
    {
      id: 4,
      width: 112,
      height: 112,
      src: "/user/user-04.png",
      alt: "User",
      name: "Cody Fisher",
      description: "I’m waiting for you response!",
      ago: "5day ago",
    },
    {
      id: 5,
      width: 112,
      height: 112,
      src: "/user/user-05.png",
      alt: "User",
      name: " Mariya Desoja",
      description: "I like your confidence 💪",
      ago: "2min ago",
    },
  ],
};
